#!/usr/bin/env bash
#bash script to install nginx on web-01 server
#Nginx should be listening on port 80
#When querying Nginx at its root / with a
#ET request (requesting a page) using curl
#it must return a page that contains the string Hello World!
apt-get -y update
apt-get -y install nginx
